apiVersion: v1
kind: Service
metadata:
  name: github-actions-exporter
  namespace: github-actions-exporter
  labels:
    app.kubernetes.io/name: github-actions-exporter
spec:
  selector:
    app.kubernetes.io/name: github-actions-exporter
  ports:
    - name: metrics
      port: 9101
      targetPort: metrics
